### ISSUE TITLE
/login : Username and password are required.

### ISSUE THREAD

**Issue by Critter** [MikeBeas/switchblade#2]
oi mate -

I did the setup. Received this:

`A new user with username "critter" was created. The user ID is 1. You have setup your Switchblade server. This function will no longer be available.`

I'm trying to login 

```
curl -X "POST" "https://xxxxx.com:500/login" \
     -H 'Content-Type: text/plain; charset=utf-8' \
     -d $'{
    "username": "critter",
    "password": "xxxxxxx"
}'
```
and am receiving this:

```
{
  "message": "Username and password are required."
}
```

any suggestions?

**Comment by MikeBeas** [comment]
Use content type application/json. The API doesn't parse plain text bodies.

**Comment by Critter** [comment]
ahh. Yeah. That sorted it. I imported the postman file into paw, and didn't take notice.

This is all nicely done and well thought out. Thanks.
