### ISSUE TITLE
NODE_ENV question

### ISSUE THREAD

**Issue by Critter** [MikeBeas/switchblade#3]
my apologies for all the questions. I'll try yo make this the last..

api works fine with `NODE_ENV=local`
but as soon as I set that to **production**, I get 'too many loop' errors. I do have SSL setup and working..

thoughts?

**Comment by MikeBeas** [comment]
I’ve never seen that error before. How far into the boot process does it get before it logs that?

**Comment by Critter** [comment]
everything runs fine. its when i try to access it from browser...

**Comment by MikeBeas** [comment]
Can you show me a screenshot? I’ve never heard of this error.

**Comment by Critter** [comment]
I shot you a message on Reddit

**Comment by MikeBeas** [comment]
ok i’m going to close this issue out and we can continue there
